version: '3.8'
services:
  next-app:
    container_name: next-app
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env

  backend:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    restart: unless-stopped
    depends_on: 
      - db
      - migrations
    env_file:
      - .env


  migrations:
    restart: on-failure
    build:
      context: ./api/sql/schema/
      dockerfile: Dockerfile
    depends_on: 
      - db
    env_file:
      - .env


  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  data: {}

